### ISSUE TITLE
Compiling on Windows 10

### ISSUE THREAD

**Issue by hacksterous** [BrianGladman/gmpy2#1]
I have got mpir, mpfr and mpc compiled as mentioned in windows_build.txt, but when I try to execute:

`c:\32\Python26\python.exe setup.py build_ext --force --mpir --static=c:\src\32\vs2008 bdist_wininst`

I see an error:

`error: option --static must not have an argument`

Without the `c:\src\32\vs2008`, I see the expected VS compiler error:

`c:\src\gmpy2\src\gmpy2.h(81): fatal error C1083: Cannot open include file: 'mpir.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2`

**Comment by BrianGladman** [comment]
The gmpy build I offer here requires mpir, mpc and gmpy2 to be placed in sub-directories within a common parent directory, i.e.:

     parent_directory
         mpir
         mpc
         gmpy2

The header files won't be found if this layout isn't being used.

**Comment by hacksterous** [comment]
As mentioned in windows_build.txt, I have all the sources in:
c:\src\mpir
c:\src\mpfr
c:\src\mpc
c:\src\gmpy2

The main issue seems to be --static=c:\src\32\vs2008

I need to pass the c:\src\ in the command line, but not with the --static option.

**Comment by BrianGladman** [comment]
There is a comment about this issue here: https://github.com/aleaxit/gmpy/issues/197   Since https://github.com/aleaxit/gmpy/ is the master repository for GMPY2, you are more likely to find help if you raise your issue there.

**Comment by rsekman** [comment]
`--static` should be `--static-dir`. I was able to build gmpy after making this change.
