### ISSUE TITLE
Intentional fallthroughs?

### ISSUE THREAD

**Issue by r-barnes** [BrianGladman/gmpy2#11]
Are the fallthroughs on these lines intentional?

https://github.com/BrianGladman/gmpy2/blob/003f3a3a876fd8dc5ff6d4f84477120d199a14a6/src/gmpy2_mpmath.c#L273
https://github.com/BrianGladman/gmpy2/blob/003f3a3a876fd8dc5ff6d4f84477120d199a14a6/src/gmpy2_mpmath.c#L279
https://github.com/BrianGladman/gmpy2/blob/003f3a3a876fd8dc5ff6d4f84477120d199a14a6/src/gmpy2_mpmath.c#L281

**Comment by BrianGladman** [comment]
This repository is simply a copy of the main gmpy2 repository in which I maintain the interface to MPIR. Questions about GMPY2 itself should be posted on the main GMPY2 repository at  https://github.com/aleaxit/gmpy

**Comment by r-barnes** [comment]
@BrianGladman - I see that the upstream code has been fixed: https://github.com/aleaxit/gmpy/blob/7bd27fe4c950075cfd65354fc955588f903bfb7d/src/gmpy2_mpmath.c#L290C13-L290C30
