### ISSUE TITLE
Update PIP binary builds

### ISSUE THREAD

**Issue by polkovnikov** [BrianGladman/gmpy2#4]
Looks like PIP binary builds are very outdated, [see here](https://pypi.org/project/gmpy2/#files), there is only Python **3.4** prebuilt version for Windows and none for Linux.

Of course you can pip-install everything from source, but building GMPY2 is quite uneasy, especially for Windows were you have to manually install Visual Studio and install/prebuild all dependend libraries. Many people can't do this. Linux version is easier to build, also prebuilt version is available through `sudo apt install python3-gmpy2`, but it would be great if also Linux prebuilt version is available through pip-install.

Very good updated binary builds of GMPY2 are [available here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gmpy), I use them often, this website has very good quality of all builds and hundreds of other prebuilt PIP binary packages, which are usually unavailable in PIP. You can just take this build from there, I tested it many times, and place it on PIP.

Also not sure if this is the right GitHub repository for reporting issues/requests for GMPY2, it was the first repository that popped up in Google. But loooks like this repo has few stars and issues, so maybe not the right place. Would be great if you suggest right place for posting issues/requests.

**Comment by BrianGladman** [comment]
The primary GIT repository for GMPY2 is at: https://github.com/aleaxit/gmpy   

I maintain this repository in order to ensure that gmpy2 and all its dependencies can be built using Microsoft Visual Studio.   I suggest that you raise this issue on the primary GITHUB repository for GMPY2.

**Comment by polkovnikov** [comment]
@BrianGladman Thanks! OK, so then closing this issue in favor of opening it on main repository.

BTW, I created same issue on main repo, [see here](https://github.com/aleaxit/gmpy/issues/313).
